name: Actualizar Tabla Futbol Chile
on:
  schedule:
    - cron: '0 14,2 * * *'       # 10 AM y 10 PM Chile
    - cron: '0 22 * * 0,3,6'     # 6 PM (Mié, Sáb, Dom)
    - cron: '0 0,4 * * 1,4,0'    # 8 PM y 12 AM (Cierres de jornada)
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests beautifulsoup4
      - run: python scraper_futbol.py
      - run: |
          git config --global user.name "Duplos Bot"
          git config --global user.email "bot@duplos.cl"
          git add futbol_chile.json
          git commit -m "⚽ Tabla actualizada" || exit 0
          git push
